### ISSUE TITLE
TODO: BackEnd

### ISSUE THREAD

**Issue by Parmifer** [Parmifer/symfony-cinEMA#1]
# MVC
  - [x] Créer une page home contenant un lien vers 
     - [x] une page 'A propos'
     - [x] une page 'Infos légales'
    
# Templating
  - [x] Dans la page 'A propos', lister les créateurs du site (à partir d'un tableau php en dur).
  - [x] Mettre en place un gabarit commun à tous les écrans
  - [x] Mettre un peu de style

# Base de données
  - [x] Afficher dans une page la liste de tous les films par ordre alphabétique
  - [x] Afficher sur la home les 3 films les plus récents
  - [x] Externaliser le nombre de films à afficher sur la home dans le fichier parameters.yml
  - [x] Créer la page de détail d'un film avec toutes ses détails
  - [x] Permettre de lister les films par genre ('action', 'thriller', 'sf')
  - [x] Lister dans le footer la liste des catégories avec le nombre de films dans chaque 
  - [x] Pour chaque film, afficher le réalisateur (Une personne avec nom et prénom) s'il est connu, 
  et un lien vers la page de la personne.
  - [x] Pour chaque film, afficher la liste des acteurs qui jouent dans le film, 
  et un lien vers la page de l'acteur)

# Formulaire
  - [x] Afficher un formulaire destiné à créer un film (titre, synopsis, genre et date de sortie)
  - [x] Traiter la soumission de ce formulaire
  - [x] Ajouter la règle, le synopsis doit faire entre 5 et 100 caractères
  - [x] Ajouter la possibilité de choisir le réalisateur et les acteurs à la création du film
  - [x] Mettre en forme le formulaire (labels et champs alignés verticalement)

# Bundle
  - [x] Optimiser le SEO en affichant le titre dans l'adresse de la page d'un film
  
# Sécurité
  - [ ] Créer une page (vide) destinée à afficher les infos de l'utilisateur connecté (HTTP 
  authentification)
  - [ ] Ajouter un lien pour se déconnecter
  - [ ] Protéger le formulaire de création de film par un accès restreint à un admin
  
# Service
  - [ ] Créer un service capable de générer un film aléatoire (sans acteurs)
  - [ ] Afficher ce film dans une page
  - [ ] Ajouter un ou plusieurs acteurs (aléatoirement) au film généré

# Internationalisation
  - [ ] Ajouter une version «anglaise» à votre site
  
# Documentation
  - [ ] Ajouter quelques logs à votre application
  - [ ] Faire sortir les logs «applicatif» dans un fichier dédié
  - [ ] Envoyer un email à l'admin du site (son email fait partie des paramètres) lorsqu'un film a 
  bien été créé. Le mail doit contenir le nom du film et un lien vers la page du film.
  - [ ] Personnaliser votre page 404
